// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoCWebApi.Data;

#nullable disable

namespace PoCWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126195856_AddRbacModel")]
    partial class AddRbacModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoCWebApi.Auth.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Description = "Read standard todos",
                            Key = "Todo.Read"
                        },
                        new
                        {
                            PermissionId = 2,
                            Description = "Create/update standard todos",
                            Key = "Todo.Write"
                        },
                        new
                        {
                            PermissionId = 3,
                            Description = "Read PII todos",
                            Key = "PII.Read"
                        },
                        new
                        {
                            PermissionId = 4,
                            Description = "Create/update PII todos",
                            Key = "PII.Write"
                        });
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Can work with non-PII Todos only",
                            Name = "CSR"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Can work with Todos and PIITodos",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.RoleService", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RoleServices");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "Standard Todo service",
                            Key = "Todo"
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "PII Todo service",
                            Key = "PIITodo"
                        });
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.ServicePermission", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ServicePermissions");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            ServiceId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            ServiceId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            ServiceId = 2,
                            PermissionId = 4
                        });
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.User", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Oid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.UserRole", b =>
                {
                    b.Property<Guid>("Oid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Oid", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("PoCWebApi.Models.PIITodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerOid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PIITitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerOid", "IsDone");

                    b.ToTable("PIITodos");
                });

            modelBuilder.Entity("PoCWebApi.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerOid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerOid", "IsDone");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.RoleService", b =>
                {
                    b.HasOne("PoCWebApi.Auth.Models.Role", "Role")
                        .WithMany("RoleServices")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoCWebApi.Auth.Models.Service", "Service")
                        .WithMany("RoleServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.ServicePermission", b =>
                {
                    b.HasOne("PoCWebApi.Auth.Models.Permission", "Permission")
                        .WithMany("ServicePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoCWebApi.Auth.Models.Service", "Service")
                        .WithMany("ServicePermissions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.UserRole", b =>
                {
                    b.HasOne("PoCWebApi.Auth.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("Oid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoCWebApi.Auth.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.Permission", b =>
                {
                    b.Navigation("ServicePermissions");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.Role", b =>
                {
                    b.Navigation("RoleServices");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.Service", b =>
                {
                    b.Navigation("RoleServices");

                    b.Navigation("ServicePermissions");
                });

            modelBuilder.Entity("PoCWebApi.Auth.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
